[VK]
; Вставьте ваш токен от группы ВК
token = vk1.a.b17HvviTbmOqh52GzSGRnE9lNKXFpKnU-X-cq88a-SZ4bQsya2iTeY0TX32ewApemF7fcJz4H8ZdwGczxlrH4mWK7fxz1H3kl1EZuYPo8cG8jgokc_2dIvc66tJnje6Sn0sUBPN7fM7NaD3mUkY2FMTDwn2sTGyvgAMuYHEqz6ANY2_DDkVncEvUdzmAcwl-6dPZPXKnwL2chdsVxd2aWg
admin_chat_id = 2000000960
[SECURITY] 
; Ключ для команды /godmode
godmode_key = malibikpolicilgodmode
[CMD_LEVELS]
; Уровни доступа к командам. 0 - доступен всем, 9 - максимальный уровень
help = 0
test = 0
admins = 0
profile = 0
logs = 6
adm = 0
setdj = 3
setrole = 4
setnick = 3
setforum = 3
warn = 4
pred = 2
unwarn = 4
unpred = 2
bllist = 3
setlvl = 6
newadmin = 6
kick = 7
reactivate = 5
editcmd = 5
bladd = 5
blrem = 5
mute = 5
unmute = 5
check_chat = 0
[CASINO]
daily_bonus = 150
min_bet = 100
max_bet = 5000